name: Deploy Testing Branch
on:
  push:
    branches: 
      - testing
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
      - name: Clone app-vlead-web
        run: git clone --depth=1 https://github.com/virtual-labs/app-vlead-web
      - name: Build experiment
        run: |
          cd ph3-lab-mgmt
          npm install
          npm run build-exp
      - name: Configure Git
        run: |
          git config --local user.email "admin@vlabs.ac.in"
          git config --local user.name "vleadadmin"
      - name: Prepare gh-pages
        run: |
          git checkout --orphan gh-pages
          git reset
          git add build/* -f
          git mv build/* ./ -f
      - name: Commit changes
        run: git commit -m "https://virtual-labs.github.io/${{ github.event.repository.name }} click on the link to test your code."
      - name: Push to gh-pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ORG_OWNER_GITHUB_TOKEN }}
          force: true
          branch: gh-pages